services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    ports:
      - "4004:4004"
      - "5173:5173"
    volumes:
      - .:/inertia_ssr_adapters
      - ./deps:/inertia_ssr_adapters/deps
      - node_modules_container:/inertia_ssr_adapters/assets/node_modules
    depends_on:
      - db
      - mailpit
    environment:
      - CHOKIDAR_USEPOLLING=true # Fix for file watching in Docker
      - MAILPIT_SMTP_HOST=inertia_ssr_adapters_mailpit
      - MAILPIT_SMTP_PORT=1025
      - PORT=4004
    # require IEx
    # In the line you want to stop:
    # IEx.pry()
    #
    # docker-compose run --service-ports web
    # Uncomment this line:
    # command: iex -S mix phx.server

    stdin_open: true
    tty: true
    networks:
      - inertia_ssr_adapters_network

  db:
    image: postgres:16
    environment:
      - "POSTGRES_USER=inertia_ssr_adapters_user"
      - "POSTGRES_PASSWORD=secret"
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - inertia_ssr_adapters_network

  # Trap emails on development
  mailpit:
    image: axllent/mailpit
    container_name: inertia_ssr_adapters_mailpit
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - inertia_ssr_adapters_network
volumes:
  # Having this volume keep inside node_modules independent of the host
  node_modules_container:

networks:
  inertia_ssr_adapters_network:
    name: inertia_ssr_adapters_network
    driver: bridge
    external: false
